[package]
name = "rpc-perf"
version = "6.0.0-alpha.0"
authors = ["Brian Martin <brayniac@gmail.com>"]
edition = "2021"
description = "RPC Performance Testing"
homepage = "https://github.com/brayniac/rpc-perf"
repository = "https://github.com/brayniac/rpc-perf"
license = "Apache-2.0"

[[bin]]
name = "rpc-perf"
path = "src/main.rs"

[dependencies]
async-channel = "1.8.0"
async-memcached = "*"
boring = "2.1.0"
bytes = "1.2.1"
clocksource = "0.6.0"
memcache-async = "*"
momento = "0.10.0"
metriken = "0.1.0"
mio = "0.8.5"
net = { path = "../pelikan/src/net" }
# protocol-common = { git = "https://github.com/pelikan-io/pelikan" }
# protocol-memcache = { path = "../pelikan/src/protocol/memcache" }
# protocol-ping = { path = "../pelikan/src/protocol/ping" }
protocol-memcache = { git = "https://github.com/pelikan-io/pelikan" }
protocol-ping = { git = "https://github.com/pelikan-io/pelikan" }
tokio = { version = "1.21.2", features = ["full"] }
rand = "*"
rand_distr = "*"
rand_xoshiro = "*"
redis = { version = "0.22.3", features = ["tokio-comp"] }
ringlog = "*"
serde = "1.0.144"
serde_derive = "1.0.144"
# session = { path = "../pelikan/src/session" }
session = { git = "https://github.com/pelikan-io/pelikan" }
slab = "*"
toml = "*"
zipf = "7.0.0"

[target.'cfg(target_os = "linux")'.dependencies]
tokio-uring = "0.4.0"

[features]
uring = []

[profile.release]
opt-level = 3
debug = true
rpath = false
lto = true
debug-assertions = false
codegen-units = 1

[profile.bench]
opt-level = 3
debug = true
rpath = false
lto = true
debug-assertions = false
codegen-units = 1

[profile.dev]
debug = true
opt-level = 0
