[general]
# specify the protocol to be used
protocol = "resp"
# the interval for stats integration and reporting
interval = 1
# the number of intervals to run the test for
duration = 300
# controls the number of worker threads to launch, each worker thread maintains
# its own event loop and connection pool to each endpoint
threads = 4
# run the admin thread with a HTTP listener at the address provided, this allows
# stats exposition via HTTP
admin = "127.0.0.1:9090"

[debug]
# choose from: error, warn, info, debug, trace
log_level = "info"
# optionally, log to the file below instead of standard out
# log_file = "rpc-perf.log"
# backup file name for use with log rotation
log_backup = "rpc-perf.log.old"
# trigger log rotation when the file grows beyond this size (in bytes). Set this
# option to '0' to disable log rotation.
log_max_size = 1073741824

[target]
# specify one or more endpoints as IP:PORT pairs
endpoints = [
	"127.0.0.1:6379",
]

[connection]
# the number of connections to each endpoint from each thread, the total number
# of connections to each endpoint is: poolsize * threads
poolsize = 20
# the connect timeout in milliseconds
timeout = 10000

[request]
# number of threads used to drive requests
threads = 4
# set a global ratelimit for requests
ratelimit = 10_000
# set the timeout in milliseconds
timeout = 1000

[workload]
# the number of threads that will be used to generate requests
threads = 1

[[workload.keyspace]]
# sets the relative weight of this keyspace: defaults to 1
weight = 1
# sets the length of the key, in bytes
klen = 32
# sets the number of keys that will be generated
nkeys = 1_000_000
# sets the value length, in bytes
vlen = 128
# use random bytes for the values
vkind = "bytes"
# controls what commands will be used in this keyspace
commands = [
	# get a value
	{ verb = "get", weight = 80 },
	# set a value
	{ verb = "set", weight = 20 },
	# delete a value
	{ verb = "delete", weight = 0 },
]

[[workload.keyspace]]
# sets the relative weight of this keyspace: defaults to 1
weight = 1
# sets the length of the key, in bytes
klen = 24
# sets the number of keys that will be generated
nkeys = 1_000_000
# sets the length of the inner key, in bytesp
inner_keys_klen = 4
# sets the number of inner keys that will be generated
inner_keys_nkeys = 1_000
# sets the value types to integers so we can mix increment with set
vkind = "i64"
# controls what commands will be used in this keyspace
commands = [
	# request a field from a discrionary
	{ verb = "hget", weight = 30 },
	# set cardinality > 1 to get multiple fields
	{ verb = "hget", weight = 10, cardinality = 5 },

	# increment a value for a field in the dictionary
	{ verb = "hincrby", weight = 10 },

	# retrieve an entire dictionary
	{ verb = "hgetall", weight = 5 },

	# delete a field from a dictionary
	{ verb = "hdel", weight = 10 },
	# set cardinality > 1 to remove multiple fields
	{ verb = "hdel", weight = 5, cardinality = 5 },

	# set a field in the dictionary
	{ verb = "hset", weight = 20 },
	# set cardinality > 1 to set multiple fields
	{ verb = "hset", weight = 5, cardinality = 5 },

	# delete an entire dictionary
	{ verb = "delete", weight = 5 }
]

[[workload.keyspace]]
# sets the relative weight of this keyspace: defaults to 1
weight = 1
# sets the length of the key, in bytes
klen = 16
# sets the number of keys that will be generated
nkeys = 1_000_000
# sets the length of the inner key, in bytesp
inner_keys_klen = 4
# sets the number of inner keys that will be generated
inner_keys_nkeys = 1_000
# controls what commands will be used in this keyspace
commands = [
	# adds a member to a sorted set
	{ verb = "zadd", weight = 5 },
	# with cardinality > 1 to add multiple members
	{ verb = "sorted_set_put", weight = 5, cardinality = 5 },

	# fetch all members in a sorted set
	# NOTE: this is using `ZUNION 1 [key] WITHSCORES` to perform this
	{ verb = "zmembers", weight = 5 },

	# get the score for a member in a sorted set
	{ verb = "zscore", weight = 5 },
	# with cardinality > 1 to get scores for multiple members
	{ verb = "zmscore", weight = 5, cardinality = 5 },

	# remove a member from a sorted set
	{ verb = "zrem", weight = 2 },
	# with cardinality > 1 to remove multiple members
	{ verb = "zrem", weight = 2, cardinality = 5 },

	# delete an entire sorted set
	{ verb = "delete", weight = 1 },

	# get the rank of a member in a sorted set
	{ verb = "zrank", weight = 40 },

	# adds to the value of a member in a sorted set
	{ verb = "zincrby", weight = 25 },
]

[[workload.keyspace]]
# sets the relative weight of this keyspace: defaults to 1
weight = 1
# sets the length of the key, in bytes
klen = 8
# sets the number of keys that will be generated
nkeys = 1_000_000
# sets the length of the inner key, in bytesp
inner_keys_klen = 4
# sets the number of inner keys that will be generated
inner_keys_nkeys = 1_000
# controls what commands will be used in this keyspace
commands = [
	# adds a member to a set
	{ verb = "sadd", weight = 60 },
	# set the cardinality > 1 to add mutiple members
	{ verb = "sadd", weight = 5, cardinality = 5 },

	# retrieve all members in the set
	{ verb = "smembers", weight = 20},

	## remove a member from the set
	{ verb = "srem", weight = 5},
	# set the cardinality > 1 to remove multiple members
	{ verb = "srem", weight = 5, cardinality = 5 },

	# remove an entire set with delete
	{ verb = "delete", weight = 5 }
]
